### ISSUE TITLE
Ensure low cardinality on the operation tag for span.processing-time

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-akka-http#31]
Given that operation names in the HTTP server and client spans are used as a `operation` tag in the span metrics we should ensure that the default behavior of this module wont result in a gazillion different metrics. The main problem at the moment is that the full request path is being used as the operation name and any variation of the path will lead to a new metric to track that particular operation. Since having identifiers in the request path is a common thing then this becomes a problem to most of our users.

There was [a bug](https://github.com/kamon-io/kamon-akka-http/issues/29) on the 1.0.0 release, which was rooted on a failed effort to reduce cardinality and we should find a proper solution to this problem. 

Possible actions I see are:
  - Being extremely conservative on the default operation name generator. If the default name for a operation was fixed (e.g. `unnamed-operation`) or with a fixed domain (e.g. use just the HTTP method name) then by default it wouldn't be possible to have cardinality explosion, but the metrics wouldn't be of much use until the users (1) add a custom name generator that makes a better job and/or (2) use the `operationName` directive in their routing tree to set decent operation names.
  - Instrument the Akka HTTP directives to somehow reconstruct the HTTP template and get operation names that are variable-free (e.g. `/users/:number/accounts/:number`). We already took a look at this idea before and it's possible, but kind of complicated. This is what I would consider the best possible solution for the default behavior but it requires a non trivial effort.

**Comment by youngce** [comment]
i have the same problem. it's slowly when i monitor in Grafana.

**Comment by matwojcik** [comment]
If I don't use any metrics is there any way to workaround it other than `operationName` directive or overriding trace name generator? Like some configuration filtering all metrics?

**Comment by kodemaniak** [comment]
I just ran into this problem. I actually think the first proposal by @ivantopo is a good one. While using something like "GET" or just "unnamed-operation" might not be very informative in the end, it has two advantages IMHO. First, at least you see something about your rest API per default, which is good. But it will not break your service (which actually happens in our case since we have a lot of requests). Second, it actually forces the user to think about his metrics if he wants to produce more reasonable metrics than the default ones. That is something you should do anyway. Therefore I think it is a good compromise and everyone will actually understand what's happening.

**Comment by francisdb** [comment]
is there a way to only get the connection/request metrics without this huge list of `span.processing-time` metrics?

**Comment by gamsd** [comment]
One more to run into this problem here. In my understanding, any of the possible actions outlined by @ivantopo would be better than the current behaviour. On the conservative defaults, I agree with @kodemaniak's argument.

For my particular use case, though, even a flag to turn this behaviour on/off would be immediately helpful, as I already rely on my own custom name generator.

**Comment by jypma** [comment]
In order not to land in aspectJ hell, how about 

(3) Write a `Directives` class (java and scala DSL) that overloads most of the `path*` directives/methods to do proper operation name creation (e.g. fixed strings stay that way, params become `{}`, etc.). Users would then import kamon's `Directives` instead of akka's.

That would be much easier to maintain, and perhaps even binary compatible across akka releases if the `Directives` class/traits are directly extended.

**Comment by anzecesar** [comment]
@jypma I think that's the way to go. I followed a similar discussion once upon a time about automatically deriving Swagger API docs from akka-http without needing to add annotations all over the place and that was the suggested solution they came up with.

Sound simple enough, except I'm not sure how to get the matched path in a way that would give me path segments other than String. 

There's https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/basic-directives/extractMatchedPath.html, but glancing at it, it's always just strings.

The reason we need that is that for example `/users/:number/accounts/:number`
can be composed in many ways. One of them (which we use) is:
```
pathPrefix("users") {
  pathPrefix(JavaUUID) { userId =>
    pathPrefix("accounts") {
      pathEnd {
         get ~ post ~ etc.
      } ~
      path(JavaUUID) { accountId => // pathPrefix if goes deeper
        get ~ put ~ etc.
      }
  }
}
```

I'm also not sure how this will handle each path directive setting/updating the operationName. I'm assuming it should be ok (I have very little experience with Kamon so far)

**Comment by ivantopo** [comment]
Hey folks! There is an open PR that solves this issue: https://github.com/kamon-io/kamon-akka-http/pull/45! There is still some extra work to be done but that PR is a great starting point.

Special thanks for @jypma for what he shared on #44! Most likely at the end we will not go in that direction, but the effort and ideas in his PR are definitely valuable, thanks!

I invite you to go over #45 and give it a try. Thanks!
