### ISSUE TITLE
HTTP/1.0 responses must not have a chunked entity

### ISSUE THREAD

**Issue by leangl** [kamon-io/kamon-akka-http#60]
After enabling Kamon 2.0 on a Play 2.7.3 project every request fails with a status code 500 and I'm seeing this error on the logs:

```[kamon.instrumentation.akka.http.ServerFlowWrapper$$anon$1@1f5fcd1c]: requirement failed: HTTP/1.0 responses must not have a chunked entity
java.lang.IllegalArgumentException: requirement failed: HTTP/1.0 responses must not have a chunked entity
at akka.http.scaladsl.model.HttpResponse.<init>(HttpMessage.scala:459)
at akka.http.scaladsl.model.HttpResponse.copy(HttpMessage.scala:491)
at akka.http.scaladsl.model.HttpResponse.withEntity(HttpMessage.scala:477)
at kamon.instrumentation.akka.http.ServerFlowWrapper$$anon$1$$anon$2$$anon$5.onPush(ServerFlowWrapper.scala:131)```

**Comment by ivantopo** [comment]
Hey @lglossman, I was investigating this a bit and looks like it has to do with HTTP2 support, do you happen to be using HTTP2 in your application?

**Comment by leangl** [comment]
@ivantopo ~~Yeah, I arrived to the same conclusion. I have an nginx in front which is probably communicating via http2 with the play instances.~~
Seems like nginx doesn't support proxying using HTTP2, so I the communication has to be happening over regular HTTP, but it still has to be related to the use of nginx since on a local development environment the error is not reproducible. Will keep digging and keep you informed.

**Comment by crow-fff** [comment]
Hi all.
The problem is that [`HttpEntity.Strict#transformDataBytes`](https://github.com/akka/akka-http/blob/5c1fcb323fd072cafbd2e21d2ca5cfa5c9f285c2/akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala#L343), which is used [here](https://github.com/kamon-io/kamon-akka-http/blob/d4c57ade8930fdfbca195d7648d29fce4cc22c87/kamon-akka-http/src/main/scala/kamon/instrumentation/akka/http/ServerFlowWrapper.scala#L116), as you can see returns `HttpEntity.Chunked`.
We can pattern match against an entity, and, if it's strict, just use a contained byte buffer.
